COMP: libminc: Define _GNU_SOURCE to enable C99 extension during introspection
This commit addresses failure to detect "round" function on
compiler like g++ 4.8.2 provided by redhat devtoolset 2 [1].

More specifically, since the macro __USE_ISOC99 wasn't defined, function
"round" declared in "mathcalls.h" (itself included from "math.h") wasn't
found during introspection.

Defining _GNU_SOURCE allows to enable c99. See features.h for more details.

Error fixed by this commit is the following:

/path/to/ITKv4/Modules/ThirdParty/MINC/src/libminc/libsrc2/hyper.c:64:1: error: redefinition of ‘round’
 round(double x)
 ^

and it is reproducible using docker-centos-build [2].

CMake macro was adapated from python-cmake-buildsystem [3]

[1] https://access.redhat.com/documentation/en-US/Red_Hat_Developer_Toolset/2/html/2.0_Release_Notes/DTS2.0_Release.html
[2] https://github.com/thewtex/docker-centos-build
[3] https://github.com/python-cmake-buildsystem/python-cmake-buildsystem/blob/d0f47193837db6ad9e08bc99617276d4a24687c3/cmake/ConfigureChecks.cmake#L415

Change-Id: Iaa1290a90bc6081d4f1784c21800c85cd4eda357