COMP: Fix macOS missing atomic header build error when using clang version 3.1
This commit fixes build errors (see below) about missing atomic header
reported on macOS 10.6 when using clang version 3.1.

Build error:

In file included from /Users/kitware/Dashboards/Stable/S-481-E-b/DTIProcess/PrivateLibrary/tensorscalars.cxx:1:
In file included from /Users/kitware/Dashboards/Stable/S-481-E-b/DTIProcess/PrivateLibrary/tensorscalars.h:4:
In file included from /Users/kitware/Dashboards/Stable/S-481-E-b/DTIProcess/PrivateLibrary/dtitypes.h:5:
In file included from /Users/kitware/Dashboards/Package/Slicer-481-package/ITKv4/Modules/Core/Common/include/itkImage.h:21:
In file included from /Users/kitware/Dashboards/Package/Slicer-481-package/ITKv4/Modules/Core/Common/include/itkImageRegion.h:31:
In file included from /Users/kitware/Dashboards/Package/Slicer-481-package/ITKv4/Modules/Core/Common/include/itkRegion.h:31:
In file included from /Users/kitware/Dashboards/Package/Slicer-481-package/ITKv4/Modules/Core/Common/include/itkObject.h:31:
In file included from /Users/kitware/Dashboards/Package/Slicer-481-package/ITKv4/Modules/Core/Common/include/itkLightObject.h:23:
In file included from /Users/kitware/Dashboards/Package/Slicer-481-package/ITKv4/Modules/Core/Common/include/itkTimeStamp.h:33:
In file included from /Users/kitware/Dashboards/Package/Slicer-481-package/ITKv4/Modules/Core/Common/include/itkAtomicInt.h:38:
/Users/kitware/Dashboards/Package/Slicer-481-package/ITKv4/Modules/Core/Common/include/itkAtomicIntDetail.h:42:11: fatal error: 'atomic'
      file not found

          ^

$ /Users/kitware/Dashboards/Support/clang+llvm-3.1-x86_64-apple-darwin11/bin/clang++ --version
clang version 3.1 (tags/RELEASE_31/final)
Target: x86_64-apple-darwin10.8.0
Thread model: posix

See also http://slicer-devel.65872.n3.nabble.com/MacOSX-factory-build-Transitioning-from-hybrid-quot-llvm-g-quot-to-quot-clang-quot-Update-to-Qt-4-8-6-tt4032198.html#a4032199

Change-Id: If72e44f76ebbc2f4006917318f1540c973e8a469
Reported-by: Juan Carlos Prieto <Juanprietob@gmail.com>